### PR TITLE
Removed "owned by an agency" :)

### PR DESCRIPTION
**Pull request by DominikAngerer**
Actually we're not owned by an agency ;)

### CODE REVIEW

**Comment by geraldb** [comment]
@DominikAngerer    ageny is just Web Medien Agentur in german. Last time at the ruby meetup you said it's part of ..... - that's the name i forgot.   Can you fill in ?    PS: Thanks for taking the time. Cheers.

**Comment by oliverjessner** [comment]
Offtopic: how about a node repo for the same things as the ruby repo :)?

**Comment by geraldb** [comment]
@oliverjessner  You're welcome to start it.  Please, do.   I'm already overstretched and, thus, can't do it.

**Comment by geraldb** [comment]
@DominikAngerer  The note is now a hidden html comment.  I close the request. Thanks again. Keep it up. Cheers.

**Comment by oliverjessner** [comment]
@geraldb I do not have the rights to open repos in austriacodes.  So I need at least one how creates an empty node repo :)

**Comment by geraldb** [comment]
@oliverjessner  sorry for the trouble - all editor have write access to all repos - will create a node repo in a minute and add it to the list. Please edit / update / change as you please. You're more than welcome.

**Comment by geraldb** [comment]
@oliverjessner   The node repo is now live @ https://github.com/austriacodes/node   Again please edit / update / change as you please.

**Pull request closed without merging**
